export const options = [
  "Messier 87",
  "Triangulum Galaxy",
  "Pinwheel Galaxy",
  "Whirlpool Galaxy",
  "Sombrero Galaxy",
  "Large Magellanic Cloud",
  "Small Magellanic Cloud",
  "Centaurus A",
  "NGC 1300",
  "Carina Nebula",
  "Tarantula Nebula",
  "Pelican Nebula",
  "Helix Nebula",
  "Ring Nebula",
  "Eagle Nebula",
  "Omega Nebula",
  "Cat's Eye Nebula",
  "Eskimo Nebula",
  "Europa's Ice Crust",
  "Ganymede's Surface",
  "Io's Volcanic Plains",
  "Titan's Methane Lakes",
  "Pluto's Heart",
  "Neptune's Storms",
  "Uranus's Rings",
  "Mercury's Craters",
  "Callisto's Impact Basins",
  "Solar Flare",
  "Lunar Eclipse",
  "Total Solar Eclipse",
  "Partial Lunar Eclipse",
  "Planetary Transit",
  "Aurora Borealis",
  "Aurora Australis",
  "Supernova Remnant",
  "Black Hole Accretion Disk",
  "Quasar Emission",
  "Gamma Ray Burst",
  "Halley's Comet",
  "Oort Cloud",
  "Kuiper Belt",
  "Interstellar Dust",
  "Zodiacal Light",
  "Cosmic Microwave Background",
];
